[#50] Creating new folder structure
fga-eps-mds/2021-1-PUMA-UserService pull request #1
Opened 2021-09-28 16:13 UTC by jpmartins201

Relacionada a Issue #50

## O que faz?

Altera a estrutura de pastas dos microsserviços

## Como validar?

Visualizar as pastas e executar os microsserviços

### Issues relacionadas
\#50

2021-09-28 21:52 UTC, LhTaira commented on src/db/DBConnection.js
> +const mongoose = require("mongoose");
Por que tem mongoose?

2021-09-29 15:58 UTC, Ed-vL commented
Ficou um index.js replicado fora da src/

2021-09-30 13:44 UTC, jpmartins201 commented on src/db/DBConnection.js
> +const mongoose = require("mongoose");
Peguei os arquivos de um exemplo da internet, esqueci de comentar essas partes que não serão utilizadas (como o mongoose)

2021-09-30 14:45 UTC, Ed-vL commented on src/db/DBConnection.js
> +const mongoose = require("mongoose");
Pode só excluir ao invés de comentar

2021-10-04 02:02 UTC, Ed-vL requested changes

2021-10-04 02:02 UTC, Ed-vL commented on src/index.js
> +<<<<<<< HEAD
Ficou um conflito aqui

2021-10-04 02:02 UTC, Ed-vL commented on src/models/User.js
> +const mongoose = require("mongoose");
E o mongoose tá aqui ainda também

2021-10-05 03:16 UTC, jpmartins201 commented on src/index.js
> +<<<<<<< HEAD
Resolvido

2021-10-05 03:19 UTC, Ed-vL approved these changes

2021-10-05 04:49 UTC, merged